services:
  pr-reviewer:
    image: pr-reviewer:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pr-reviewer
    restart: unless-stopped
    env_file:
      - env/.env.example
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - reviewer-network

  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - env/.env.example
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 30s
    networks:
      - reviewer-network

  api-docs:
    image: swaggerapi/swagger-ui
    container_name: api-docs
    ports:
      - "8081:8080"
    environment:
      - SWAGGER_JSON=/openapi.yaml
    volumes:
      - ./api/openapi.yaml:/openapi.yaml
    networks:
      - reviewer-network
    profiles:
      - dev

volumes:
  pgdata:


networks:
  reviewer-network:
    driver: bridge
